### ISSUE TITLE
Documentation Suggestion  - USB-C

### ISSUE THREAD

**Issue by PCOWandre** [helloavo/Light-L16-Archive#1]
Heya! I found that on a USB-A to USB-C cable, the camera wouldn't allow me to select USB mode from notifications. When I switched to a USB-C on both ends, it allowed me to choose the correct USB mode. WIth the mode wrong, it would not allow copying to the internal storage, only accessing the DCIM and Pictures directories.

**Comment by Modd3d** [comment]
That's because your specific USB A to C cable doesn't have all the wires for data transfer try a different one

**Comment by helloavo** [comment]
I use a A -> C cable, no problems. 
As @ModdedPro says, make sure it is not a charging only cable.
